### ISSUE TITLE
vpn client and server can ping pong but unable to send internet traffic in win 11 through vpn tunnel

### ISSUE THREAD

**Issue by mrgspeed** [Doridian/wsvpn#254]
hello , i have setup some basic client and server configs, and i can see client and server are ping ponging with each other, but issue i have is that windows 11 is not sending any traffic through vpn tunnel , i do have  "tunnel:  set-default-gateway: true"
  here are my configs

  server:

```
tunnel:
    subnet: 192.168.13.0/24

server:
    listen: ":9000"
    enable-http3: true # Specify this if you want to use WebTransport as well
    authenticator:
        type: "htpasswd"
        config: "1.htpasswd" # Filename of a file in htpasswd format. Created as outlined above.
    tls:
        key: "key.pem" # Filename of a PEM formatted private key
        certificate: "cert.pem" # Filename of a PEM formatted certificate (with chain if applicable)
```

client
```
tunnel:
  set-default-gateway: true
  ping:
    interval: 25s
    timeout: 5s
  features:
    fragmentation: true # Enable packet fragmentation (default enabled), required for MTU > 1216 in WebTransport
    datagram_id_0: true

interface:
  name: ""
  persist: false
  component-id: root\tap0901 # Windows only. Defaults: root\tap0901 or tap0901

scripts:
  # These scripts get run as "args... operation subnet interface"
  # Pass in an array, first argument is the executable, further arguments
  # are used before WSVPN provided arguments
  # Example: "./handler.sh up 192.168.3.2/24 tun0"
  up: []
  down: []

client:
  server: "wss://mrg:acerv551@de2ws.efjefe.efpjefjh.qwdofjwej.rgfik.mrgspeed.site:9000" # Examples: ws://example.com:9000 wss://secure.example.com:9000
  proxy: "" # Example: http://user:password@proxy.example.com:8080
  auth-file:  "" # Filename of file containing user:password for HTTP Basic authentication
  auto-reconnect-delay: 1s # Delay after which to retry connecting to the server automatically after an error, set to 0s (default) to disable

  headers: # Map of headers (string key to *list* of string values)
  # Host:
  #   - example.com
  # X-Other-Header:
  #   - value1
  #   - value2

  tls:
    ca: "" # Filename of CA bundle for verifying server cert
    certificate: "" # Filename of certificate for mTLS
    key: "" # Filename of private key for mTLS
    server-name: "" # If not blank, the hostname to check for in the SSL certificate. If blank, uses hostname from server URL
    config:
      insecure: true
      min-version: 1.2
      max-version: 1.3
      cipher-preference: "" # blank, AES or CHACHA
      key-log-file: "" # This will log TLS secret keys to a file. DO NOT USE IN PRODUCTION!
```
